from database import SessionLocal
from sqlalchemy import text

questions = [
    {"question": "Define electric traction and its primary applications.", "ideal_answer": "Electric traction refers to the use of electric power to provide motive force for vehicles like railways, trams, and trolleys. It typically utilizes DC motors or specialized AC motors for high starting torque and efficient speed control."},
    {"question": "Is it possible to start a 40W fluorescent tube without a choke or coil?", "ideal_answer": "It is possible using an electronic ballast (electronic choke), which uses high-frequency switching to ionize the gas. Without specialized electronic circuitry, a traditional magnetic choke is required to provide the high voltage kick for ionization."},
    {"question": "What does 'per unit' (pu) signify in electrical power systems?", "ideal_answer": "Per unit (pu) is a normalized value used to simplify power system calculations. It is defined as the ratio of the actual value to a chosen base value (actual/base). This allows components with different ratings (KV, MVA) to be analyzed on a common scale."},
    {"question": "Describe the basic energy conversion process in a thermal power plant.", "ideal_answer": "Coal is burned in a boiler to heat water into high-pressure steam. This steam strikes a turbine, converting thermal energy into mechanical energy. The turbine is coupled to a generator, which converts mechanical energy into electricity."},
    {"question": "Why is a fuse placed in the phase wire while a link is used in the neutral wire?", "ideal_answer": "A fuse is a safety device placed in the live (phase) wire to interrupt current during a fault. The neutral wire is kept continuous with a link to ensure a return path for current and to maintain a stable reference point, preventing floating neutral voltages."},
    {"question": "Explain the working principle of a traditional starter and choke in a tube light circuit.", "ideal_answer": "The starter acts as a timed switch that allows the choke (inductor) to build up energy. When the starter opens, the choke induces a high voltage spike (~1000V) to ionize the gas in the tube. Once the arc is established, the choke limits the steady-state current."},
    {"question": "What is a Marx Circuit and its typical use?", "ideal_answer": "A Marx Circuit is used to generate high-voltage impulses. It works by charging multiple capacitors in parallel at low voltage and then discharging them in series to achieve a very high output voltage for testing insulation and lightning studies."},
    {"question": "Define an encoder and its general function.", "ideal_answer": "An encoder is a device that converts physical motion or an analog signal into a digital code. It is often used in feedback systems to track position, speed, or direction of a rotating shaft."},
    {"question": "What are the advantages of using thyristors for motor speed control?", "ideal_answer": "Thyristors (SCRs) offer fast switching, high efficiency, compact size, and high reliability compared to older mechanical or rheostatic control methods. They are excellent for handling high currents in industrial drives."},
    {"question": "Why does a human feel an electric shock, and why is it usually avoided in well-insulated systems?", "ideal_answer": "A shock occurs when the human body becomes part of a closed electrical circuit, allowing current to flow through tissues. Insulation (like rubber footwear or equipment enclosures) prevents this by providing a high-resistance path that blocks the flow of current."},
    {"question": "State the fundamental principle of an electric motor.", "ideal_answer": "An electric motor operates on the principle that a current-carrying conductor placed within a magnetic field experiences a mechanical force (torque), as described by Lorentz force law."},
    {"question": "Why can birds sit on a single high-voltage wire without getting electrocuted?", "ideal_answer": "A bird sitting on a single wire is at the same potential as the wire. Since there is no potential difference (and no path to ground or another phase), no current flows through the bird's body. If the bird touched two wires or a wire and a grounded pole, it would be shocked."},
    {"question": "What is 'armature reaction' in a DC machine?", "ideal_answer": "Armature reaction is the effect of the magnetic field produced by the armature current on the main magnetic field produced by the field poles. It can cause distortion or weakening of the main flux, leading to commutation issues."},
    {"question": "What happens if a standard inductive AC load (like a fluorescent tube with a choke) is given a DC supply?", "ideal_answer": "In DC, an inductor acts as a low-resistance path after the initial transient. Without the impedance provided by AC frequency, the current can rise to dangerously high levels, potentially burning out the coil or the device."},
    {"question": "Which motor provides the highest starting torque?", "ideal_answer": "The DC Series motor is renowned for its exceptionally high starting torque, making it ideal for heavy-duty applications like electric locomotives and cranes."},
    {"question": "What is ACSR cable and where is it commonly used?", "ideal_answer": "ACSR stands for Aluminum Conductor Steel Reinforced. It consists of aluminum strands for conductivity and a steel core for mechanical strength. It is widely used for overhead transmission and distribution lines."},
    {"question": "Explain the role of the medium in a Vacuum Circuit Breaker (VCB).", "ideal_answer": "In a VCB, the contacts open inside a vacuum. Because there are no gas molecules to ionize, the arc is quenched almost instantly, making it highly effective for high-voltage switching with minimal maintenance."},
    {"question": "How does a leading power factor affect a distribution network?", "ideal_answer": "A leading power factor (often caused by over-excitation or capacitor banks) can help neutralize lagging currents, reducing overall line losses and improving voltage levels. However, excessive leading PF can cause over-voltages at the receiving end (Ferranti effect)."},
    {"question": "Compare a UPS and an Inverter.", "ideal_answer": "A UPS (Uninterruptible Power Supply) provides near-instantaneous switchover (milliseconds) to battery power, making it suitable for computers. An Inverter typically has a longer switchover time and is used for general home backup where a brief power gap is acceptable."},
    {"question": "What is a two-phase motor and provide an example?", "ideal_answer": "A two-phase motor uses two windings with a 90-degree phase shift to create a rotating magnetic field. An example is the AC Servo motor used in precision control systems."},
    {"question": "Define VVVF drives and their benefit for industrial cranes.", "ideal_answer": "VVVF (Variable Voltage Variable Frequency) drives allow for smooth acceleration and deceleration of motors. This eliminates mechanical jerks, allows for precise positioning of loads, and extends the lifespan of the motor and hoist mechanisms."},
    {"question": "What is the significance of the vector group in a power transformer?", "ideal_answer": "The vector group indicates the winding connections (Star, Delta) and the phase displacement between the primary and secondary sides. Correct matching is essential for connecting transformers in parallel."},
    {"question": "Describe the type of AC motor used in most ceiling fans.", "ideal_answer": "Ceiling fans typically use a single-phase induction motor, specifically a permanent split-capacitor (PSC) motor, which uses a capacitor to create the necessary phase shift for starting and running."},
    {"question": "Explain the 'Flux Control' method for DC shunt motor speed regulation.", "ideal_answer": "By adding a rheostat in series with the field winding, you can vary the field current. Reducing the current weakens the flux, which increases the motor speed, as speed is inversely proportional to flux."},
    {"question": "What is the primary difference between a synchronous and an asynchronous (induction) generator?", "ideal_answer": "A synchronous generator can provide both active and reactive power and its speed is locked to the frequency. An induction generator typically requires an external source for reactive power (excitation) and runs slightly above synchronous speed."},
    {"question": "What is the Polarization Index (PI)?", "ideal_answer": "The Polarization Index is the ratio of the insulation resistance measured after 10 minutes to the resistance measured after 1 minute. It is a key indicator of the health and cleanliness of motor or transformer insulation."},
    {"question": "Define the function of an Automatic Voltage Regulator (AVR).", "ideal_answer": "An AVR monitors the output voltage of a generator and automatically adjusts the excitation current to maintain a constant voltage level, even as the load varies."},
    {"question": "What is an 'Exciter' in a generator system?", "ideal_answer": "An exciter is a device (either a small DC generator or a rectified AC source) that provides the DC current needed to create the magnetic field in the main rotor of a synchronous generator."},
    {"question": "Contrast a three-point starter and a four-point starter for DC motors.", "ideal_answer": "A three-point starter's 'No Volt Coil' is in series with the field, which can cause the handle to drop if speed is increased via field weakening. A four-point starter connects the coil independently across the line, allowing for a wider range of speed control without tripping."},
    {"question": "Why is a Vacuum Circuit Breaker (VCB) preferred over an Air Circuit Breaker (ACB) for high-voltage systems?", "ideal_answer": "Vacuum has significantly higher dielectric strength than air (about 8 times higher), allowing for much smaller contact gaps and more effective arc quenching at high voltages."},
    {"question": "What is the difference between a lightning arrestor and a surge arrestor?", "ideal_answer": "A lightning arrestor is installed externally to divert high-voltage atmospheric strikes to the ground. A surge arrestor is typically installed internally to protect sensitive electronic components from switching surges or smaller transients."},
    {"question": "How does connecting a capacitor bank affect an AC generator?", "ideal_answer": "A capacitor bank improves the power factor by providing reactive power locally. This reduces the reactive burden on the generator, allowing it to deliver more active power (KW) without overheating, provided it is not over-excited."},
    {"question": "Why do capacitors block DC but allow AC to pass?", "ideal_answer": "A capacitor consists of an insulator between two plates. DC current cannot flow through the insulator once the plates are charged. However, AC continuously charges and discharges the plates, creating a displacement current that 'passes' through the circuit."},
    {"question": "Explain the concept of 'Anti-pumping' in a circuit breaker.", "ideal_answer": "Anti-pumping is a safety feature that prevents the breaker from repeatedly opening and closing ('pumping') if a close command is held while a trip condition exists. It ensures the breaker stays open until the signal is reset."},
    {"question": "What is a Stepper Motor and where is it used?", "ideal_answer": "A stepper motor is a brushless DC motor that divides a full rotation into a number of equal steps. It is used in applications requiring precise position control, such as 3D printers, CNC machines, and robotics."},
    {"question": "Briefly explain the roles of Current Transformers (CT) and Potential Transformers (PT).", "ideal_answer": "CTs and PTs are instrument transformers used to scale down high currents and voltages to safe, measurable levels (e.g., 5A or 110V) for meters and protection relays."},
    {"question": "Definition and importance of 'Power Factor'.", "ideal_answer": "Power factor is the ratio of real power (W) to apparent power (VA). A high power factor (close to 1.0) means the system is using energy efficiently with minimal reactive power waste, reducing heating and allowing for smaller cable sizes."},
    {"question": "What is a Buchholz Relay?", "ideal_answer": "A Buchholz Relay is a gas-actuated safety device installed on oil-immersed transformers. It detects internal faults (like short circuits or insulation breakdown) by sensing the gases generated by the decomposition of the oil."},
    {"question": "Define the 'Ferranti Effect'.", "ideal_answer": "The Ferranti Effect occurs in long transmission lines under no-load or light-load conditions, where the receiving end voltage becomes higher than the sending end voltage due to the line's capacitance."},
    {"question": "What is the difference between an MCB and an MCCB?", "ideal_answer": "An MCB (Miniature Circuit Breaker) is used for low-current applications (up to 100A), usually in homes. An MCCB (Molded Case Circuit Breaker) is for higher current ranges (up to 2500A) and often has adjustable trip settings for industrial use."},
    {"question": "Define an IDMT Relay.", "ideal_answer": "IDMT stands for Inverse Definite Minimum Time. It is a protection relay where the tripping time is inversely proportional to the fault current—higher currents result in faster trips."},
    {"question": "Explain the 'inrush current' in electrical transformers.", "ideal_answer": "Inrush current is the instantaneous surge of current that occurs when a transformer is first energized. It happens due to the saturation of the core and can be many times the rated full-load current."},
    {"question": "Why is the earth pin in a three-pin plug longer and thicker than the others?", "ideal_answer": "The earth pin is longer to ensure it makes contact first (safety grounding) and breaks contact last. It is thicker to prevent it from being inserted into the live or neutral holes erroneously."},
    {"question": "Why do we use 50Hz or 60Hz as standard frequencies?", "ideal_answer": "These frequencies are a balance between efficiency (lower frequencies cause light flickering) and size (higher frequencies allow for smaller transformers but increase line losses). Standards were established early in the power industry to ensure equipment compatibility."},
    {"question": "How are battery banks typically connected and why?", "ideal_answer": "Batteries are connected in series to increase the total voltage (summing the individual voltages) while keeping the same AH capacity. Parallel connection is used to increase current capacity while keeping the same voltage."},
    {"question": "What is a 'Differential Amplifier'?", "ideal_answer": "A differential amplifier amplifies the difference between two input signals while rejecting signals that are common to both inputs (like noise), characterized by its Common Mode Rejection Ratio (CMRR)."},
    {"question": "What does 'Zener Breakdown' signify in a diode?", "ideal_answer": "Zener breakdown occurs in heavily doped PN junctions where a strong electric field pulls electrons directly out of their covalent bonds, allowing current to flow in reverse at a specific, stable voltage."},
    {"question": "Compare JFET and MOSFET input impedance.", "ideal_answer": "Both have high input impedance, but MOSFETs are generally even higher because the gate is physically isolated from the channel by a thin oxide layer, resulting in almost zero gate current."},
    {"question": "Explain the purpose of the 'Extern C' linkage in C++ (for Electrical/Embedded developers).", "ideal_answer": "It tells the C++ compiler to disable name mangling for specific functions, allowing C++ code to correctly link with functions written in C, which is common when interfacing with low-level drivers or hardware libraries."},
    {"question": "What is the 'Skin Effect' in conductors?", "ideal_answer": "Skin effect is the tendency of AC current to flow primarily near the surface of a conductor. This effectively reduces the cross-sectional area and increases the resistance at higher frequencies."}
]

def import_questions():
    db = SessionLocal()
    try:
        print(f"Importing {len(questions)} Electrical interview questions...")
        for q in questions:
            db.execute(text(
                "INSERT INTO interview_questions (branch, question, ideal_answer) VALUES ('Electrical', :q, :a)"
            ), {"q": q["question"], "a": q["ideal_answer"]})
        db.commit()
        print("Successfully imported Electrical questions.")
    except Exception as e:
        print(f"Error during import: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    import_questions()
