from database import SessionLocal
from sqlalchemy import text

questions = [
    {"question": "What are the primary causes of building structural failure or collapse?", "ideal_answer": "Building collapses can occur due to aged or deteriorating materials, inadequate foundation design, or external environmental factors like earthquakes, hurricanes, and floods. Non-natural causes include deliberate demolition, structural overloading, or poor construction quality."},
    {"question": "Explain the significance of the 'Modulus of Elasticity' in construction materials.", "ideal_answer": "Modulus of Elasticity (E) measures a material's stiffness or resistance to elastic deformation under stress. High E-value materials like steel (~200 GPa) are stiffer and deflect less than materials like aluminum (~70 GPa), which is nearly three times more flexible."},
    {"question": "Distinguish between routine and major maintenance in public facilities.", "ideal_answer": "Routine maintenance involves consistent, minor repairs such as painting, fixture replacement, and patching cracks to prevent deterioration. Major maintenance refers to large-scale rehabilitation, such as total structural retrofitting or complete replacement of electrical and plumbing systems."},
    {"question": "Describe the general process of constructing a freeway bridge.", "ideal_answer": "Bridges are typically built by installing reinforced concrete or steel stanchions to support the weight. The deck is formed using pre-cast concrete slabs or steel-concrete composite platforms lifted by cranes, with integrated on-ramps and off-ramps designed for expected traffic loads."},
    {"question": "What is the difference between absorption and adsorption in materials science?", "ideal_answer": "Absorption is a bulk phenomenon where substance molecules enter the entire volume of a liquid or solid. Adsorption is a surface-level phenomenon where molecules or atoms accumulate only on the outer surface of a material, forming a molecular film."},
    {"question": "In what units is concrete volume typically measured on construction sites?", "ideal_answer": "Concrete is commonly measured in cubic feet, cubic yards, or cubic meters (SI units), depending on the regional standard and the size of the project."},
    {"question": "What is the purpose of alloying metals in engineering?", "ideal_answer": "Alloying is done to achieve specific material properties such as increased strength, better corrosion resistance, or lowered melting points (as in solder). This is achieved through methods like hot pressing, rolling, or adding elements to molten base metals."},
    {"question": "Define 'braced excavation' and its primary purpose.", "ideal_answer": "Braced excavation involves using structural supports (struts, rakers, or tie-backs) to prevent the collapse or cave-in of unstable soil during deep digging operations, protecting both the workers and neighboring structures."},
    {"question": "What is meant by 'soil reinforcement' in civil engineering?", "ideal_answer": "Soil reinforcement improves the mechanical strength of soil to support heavier loads. Common techniques include mixing soil with lime or cement (chemical stabilization) or using geo-synthetics like geo-grids to provide tensile stability in embankments."},
    {"question": "How is the power of a centrifugal pump determined?", "ideal_answer": "Input power is calculated using the rated voltage, current, and efficiency (Power = V * I * sqrt(3) * Eff for 3-phase). Output is measured by the pump's capacity, typically rated in Gallons Per Minute (GPM) or cubic meters per hour."},
    {"question": "Explain the difference between a nautical mile and a statute mile.", "ideal_answer": "A nautical mile is based on one minute of latitude arc (~1852 meters). A statute mile is a standardized unit of distance (~1609 meters) originally based on a specific number of paces."},
    {"question": "Define 'absolute pressure' in fluid mechanics.", "ideal_answer": "Absolute pressure is the total pressure relative to a perfect vacuum. It is calculated by adding the atmospheric pressure (~14.7 psi at sea level) to the measured gauge pressure."},
    {"question": "What is 'Gravity Flow' in hydraulic systems?", "ideal_answer": "Gravity flow occurs when a fluid moves solely due to gravitational force rather than an applied pressure head or pump. Calculations typically omit the pressure term from the Bernoulli equation in such cases."},
    {"question": "Distinguish between engineering stress and true stress.", "ideal_answer": "Engineering stress is calculated using the original cross-sectional area of the material. True stress accounts for the actual, localized reduction in area that occurs as the material deforms and 'necks' under load."},
    {"question": "What is a 'kip' in structural engineering?", "ideal_answer": "A 'kip' is a unit of force equivalent to 1,000 pounds (1 kilo-pound). It is commonly used in structural design to avoid large numbers in pound-force units."},
    {"question": "Why does soil pressure increase with depth?", "ideal_answer": "Soil pressure increases linearly with depth due to the 'overburden'—the weight of the soil layers above. The pressure at any given point is the product of the soil's unit weight and the depth from the surface."},
    {"question": "Why are geotechnical site investigations necessary before construction?", "ideal_answer": "Investigations are conducted to determine soil bearing capacity, moisture content, and chemical composition. This ensures the site is suitable for the intended structure and informs the design of the foundation system."},
    {"question": "What is 'honeycombing' in concrete and how is it caused?", "ideal_answer": "Honeycombing refers to voids or air pockets in cured concrete where mortar failed to fill the gaps between coarse aggregate. It is typically caused by improper vibration or a mix that is too dry during placement."},
    {"question": "Explain the purpose of expansion joints in bridge decks.", "ideal_answer": "Expansion joints (the gaps in the road) allow the bridge structure to expand and contract naturally with temperature fluctuations, prevents cracking or buckling of the concrete or steel components."},
    {"question": "How do you calculate the weight of a cubic yard of concrete vs. soil?", "ideal_answer": "Soil typically weighs around 110 lbs/cu-ft (~2970 lbs/yard), while concrete is much denser at roughly 150 lbs/cu-ft (~4050 lbs/yard)."},
    {"question": "Define the 'Moment of Inertia' and its relevance to structural members.", "ideal_answer": "The Moment of Inertia (I) measures a physical body's resistance to rotational acceleration or bending. In civil engineering, it is critical for determining how beams and columns will deflect or buckle under load."},
    {"question": "Compare Quality Assurance (QA) and Quality Control (QC) in project management.", "ideal_answer": "QA is process-oriented, focusing on preventing defects through adequate project methodology. QC is product-oriented, focusing on identifying defects in the final output through testing and inspection."},
    {"question": "How do Roman aqueducts maintain water flow over long distances?", "ideal_answer": "Aqueducts rely on a constant, slight downhill gradient from a higher-elevation source to a lower-elevation destination. Roman engineers used arches and tunnels to maintain this slope, even over valleys and through hills."},
    {"question": "Why is salt water particularly damaging to Reinforced Cement Concrete (RCC)?", "ideal_answer": "Chloride ions in salt water penetrate concrete and corrode the internal steel reinforcement. Corroded steel expands, causing the surrounding concrete to spall, crack, and lose structural integrity."},
    {"question": "What does the color code for utility marking flags indicate (e.g., Blue, Red, Yellow)?", "ideal_answer": "In standard marking: Blue indicates water lines, Red indicates electric power, Yellow indicates natural gas/steam, Green signifies sewer lines, and Orange is for telecommunications/fiber optics."},
    {"question": "Explain the function of a diversion tunnel in dam construction.", "ideal_answer": "A diversion tunnel is bored through rock adjacent to a dam site to temporarily reroute the river, allowing the dam to be constructed in a dry, stable area."},
    {"question": "Why was steel favored over plain concrete for early skyscrapers like the Empire State Building?", "ideal_answer": "Steel offers superior tensile strength and flexibility (to sway in wind) compared to plain concrete. To support such height, a concrete-only building would require massive, impractical columns at its base."},
    {"question": "What is the standard unit weight of normal-weight concrete?", "ideal_answer": "Normal-weight concrete typically has a unit weight of approximately 145 to 150 pounds per cubic foot (PCF)."},
    {"question": "Distinguish between shear strength and tensile strength in fasteners.", "ideal_answer": "Tensile strength is the resistance to a force pulling along the bolt's axis. Shear strength is the resistance to a force acting perpendicular to the bolt's axis, trying to 'cut' across its diameter."},
    {"question": "Does a person climbing into a 55-gallon drum of water increase its total weight?", "ideal_answer": "Yes. Since a person is typically denser than water (or only slightly less so if floating), the total weight becomes the sum of the drum, the water, and the person's body weight."},
    {"question": "What is the purpose of using oval holes for bolts in steel rail joints?", "ideal_answer": "Oval holes allow for longitudinal expansion and contraction of the rails due to temperature changes without shearing the bolts, and also help in tightening or loosening the joint easily."},
    {"question": "What are the core responsibilities of a Construction Manager?", "ideal_answer": "Responsibilities include cost estimation, scheduling, procurement of materials, bidder selection, contract negotiation, and on-site supervision to ensure safety and quality standards are met."},
    {"question": "Define 'OSHA Compliance' in the context of construction safety.", "ideal_answer": "OSHA compliance means adhering to the Occupational Safety and Health Administration's standards to provide a safe workplace. This includes fall protection, trench safety, and proper use of personal protective equipment (PPE)."},
    {"question": "List the four critical elements of a secure hazardous waste landfill.", "ideal_answer": "Modern landfills require a bottom liner to prevent soil contamination, a leachate collection system to capture runoff, a surface cover to seal waste, and a natural hydrogeologic setting that resists water infiltration."},
    {"question": "What are 'slip joints' in seawall construction?", "ideal_answer": "Slip joints are vertical planes that allow for differential settlement between adjacent panels of a seawall. They enable movement without causing cracks in the entire unit while maintaining lateral earth pressure resistance."},
    {"question": "Explain why two gate valves are often used for a single washout point in water mains.", "ideal_answer": "Using two valves—one normally open and one normally closed downstream—ensures the branch pipe stays full of water. This prevents air pockets, reduces the risk of leakage, and allows for immediate detection of a failing valve."},
    {"question": "What is 'preset' in bridge bearing installation?", "ideal_answer": "Preset involves offsetting the top plate of a bearing to account for future irreversible movements (like creep or shrinkage). This ensures that after the structure stabilizes, the bearing sits in its ideal, centered position."},
    {"question": "Why are concrete safety barriers curved (e.g., Jersey barriers)?", "ideal_answer": "The curve is designed to redirect a vehicle back into its lane by allowing the tire to ride up the slope. This minimizes the risk of the vehicle overturning or rebounding violently into other traffic."},
    {"question": "Explain why separation membranes (like polythene) are used under concrete pavement slabs.", "ideal_answer": "The membrane reduces friction between the slab and the sub-base, allowing the concrete to expand and contract freely. It also prevents the dry sub-base from absorbing essential water from the fresh concrete mix."},
    {"question": "What are 'mud waves' in land reclamation and how can they be mitigated?", "ideal_answer": "Mud waves are lateral displacements of soft marine soil under the weight of new fill. Mitigation involves removing the displaced mud, using band drains to accelerate consolidation, or surcharging the area to force water out."},
    {"question": "Define 'True Slump', 'Shear Slump', and 'Collapse Slump' in concrete testing.", "ideal_answer": "True slump is an even subsidence of the mix. Shear slump indicates a lack of cohesion where part of the mix slides off. Collapse slump means the mix is too wet and has completely failed as a structural mass."},
    {"question": "Why is 'propping' required after formwork removal in long-span structures?", "ideal_answer": "Propping is used to prevent excessive 'creep deflection' (slow sagging over time) until the concrete has reached its full design strength and the structure can independently support its final loads."},
    {"question": "What is 'cavitation' in hydraulic pipes and why is it harmful?", "ideal_answer": "Cavitation is the formation and sudden collapse of vapor bubbles due to low-pressure regions. The resulting shockwaves can pit, erode, and eventually destroy the interior walls of pipes and pumps."},
    {"question": "What are 'bursting reinforcements' in prestressed concrete?", "ideal_answer": "These are localized reinforcements (typically spirals or mats) placed near anchorages to resist high tensile 'bursting' forces that occur where the concentrated prestressing force spreads into the concrete member."},
    {"question": "Define the 'Workability' of concrete.", "ideal_answer": "Workability is the ease with which fresh concrete can be mixed, transported, placed, and compacted without significant segregation. It is often measured using the slump test."},
    {"question": "Explain 'Cement Soundness'.", "ideal_answer": "Soundness is the ability of set cement paste to retain its volume. Unsound cement undergoes excessive expansion after setting, which can lead to severe cracking and structural failure."},
    {"question": "What are the common mix ratios for M15 and M20 grade concrete?", "ideal_answer": "M15 typically uses a 1:2:4 ratio (Cement:Sand:Aggregate). M20 uses a 1:1.5:3 ratio. High-strength grades like M30 and above usually require precise design mixes based on material testing."},
    {"question": "What is the function of a 'Spirit Level' and 'Dumpy Level' on a construction site?", "ideal_answer": "A spirit level checks the horizontal or vertical alignment of small surfaces. A dumpy level is an optical instrument used to establish or transfer accurate elevations (heights) over large distances."},
    {"question": "Why is it important to provide a specific 'Concrete Cover' over steel reinforcement?", "ideal_answer": "Cover protects the steel from environmental moisture (preventing rust) and provides thermal insulation during a fire, ensuring the core reinforcement remains strong enough to prevent structural collapse."},
    {"question": "How do you calculate the weight of a steel rebars based on its diameter?", "ideal_answer": "The unit weight is typically calculated using the formula Weight = (D^2 / 162) kg per meter, where D is the diameter of the bar in millimeters."}
]

def import_questions():
    db = SessionLocal()
    try:
        print(f"Importing {len(questions)} Civil interview questions...")
        for q in questions:
            db.execute(text(
                "INSERT INTO interview_questions (branch, question, ideal_answer) VALUES ('Civil', :q, :a)"
            ), {"q": q["question"], "a": q["ideal_answer"]})
        db.commit()
        print("Successfully imported Civil questions.")
    except Exception as e:
        print(f"Error during import: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    import_questions()
