import json
import ollama
from sqlalchemy import text
from database import mysql_engine as engine

def generate_questions_ai(branch, category, area, difficulty_text, count=1):
    """
    Generate questions using Ollama (Llama 3.1) and save to database.
    Returns list of newly generated question IDs.
    """
    new_ids = []
    
    # Map difficulty text to numeric level for prompt and DB
    diff_map = {"easy": 3, "medium": 6, "hard": 9}
    diff_level = diff_map.get(difficulty_text.lower(), 5)

    prompt = f"""Generate {count} multiple choice question(s) (MCQs) for the following topic:
- Branch: {branch}
- Category: {category}
- Topic/Area: {area}
- Difficulty Level: {difficulty_text} ({diff_level}/10)

Return ONLY a JSON array of objects with this exact structure:
[
    {{
        "question": "Clear and concise question text",
        "option_a": "First option",
        "option_b": "Second option",
        "option_c": "Third option",
        "option_d": "Fourth option",
        "correct_answer": "A",
        "explanation": "Brief explanation of the answer (2-3 sentences)"
    }}
]
"""
    try:
        print(f"🤖 AI Generating {count} questions for {area} ({branch})...")
        response = ollama.chat(
            model='llama3.1:latest',
            messages=[{'role': 'user', 'content': prompt}],
            options={'temperature': 0.7}
        )
        
        content = response['message']['content'].strip()
        
        # Basic JSON cleanup
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
            
        questions_data = json.loads(content)
        if not isinstance(questions_data, list):
            questions_data = [questions_data]

        with engine.connect() as conn:
            for q in questions_data:
                # Basic validation
                if not all(k in q for k in ["question", "option_a", "option_b", "option_c", "option_d", "correct_answer"]):
                    continue
                
                res = conn.execute(text("""
                    INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, difficulty_level, area, branch, category)
                    VALUES (:q, :a, :b, :c, :d, :ans, :exp, :diff, :dl, :area, :branch, :cat)
                """), {
                    "q": q["question"],
                    "a": q["option_a"],
                    "b": q["option_b"],
                    "c": q["option_c"],
                    "d": q["option_d"],
                    "ans": q["correct_answer"].strip().upper(),
                    "exp": q.get("explanation", "Generated by AI"),
                    "diff": difficulty_text,
                    "dl": diff_level,
                    "area": area,
                    "branch": branch,
                    "cat": category.lower()
                })
                conn.commit()
                # Use insert_id to get the last inserted ID
                # In SQLAlchemy engine.connect(), we might need a separate query or result.lastrowid
                qid_res = conn.execute(text("SELECT LAST_INSERT_ID()"))
                new_ids.append(qid_res.fetchone()[0])
                
        print(f"✅ Successfully generated and saved {len(new_ids)} questions.")
        return new_ids

    except Exception as e:
        print(f"❌ AI Generation Error: {e}")
        return []
